### ISSUE TITLE
Could you provide some installation tips for the LS-XHL and LS-CHLv2

### ISSUE THREAD

**Issue by ClashTheBunny** [mwalle/u-boot#1]
I would like to mainline the u-boot on my LS-XHL but don't know if I should just compile this and replace the u-boot_lsxh.bin in my /boot partition.  Is it safe if I don't have JTAG or serial on my NAS?  Any other tips would be much appreciated!

Thank you!

**Comment by mwalle** [comment]
see also http://git.denx.de/?p=u-boot.git;a=commit;h=43730ba72c176ffc4d9858249475f458203d9757
