### ISSUE TITLE
New Debian Kernel Boot on LS-XHL

### ISSUE THREAD

**Issue by ClashTheBunny** [mwalle/u-boot#4]
I'm unable to get the linux-image-3.16.0-4-kirkwood kernel to boot.  I have a few things that should make it pretty brain dead, including dropbear in my initrd, so I think it's failing fairly early.  I don't have serial console and I can't get netconsole working after the u-boot command.  I think it never gets to the mount stage because I don't get logs on my disk.

Are you having any problems with this?  Any suggestions on what to try?

**Comment by mwalle** [comment]
sorry for the late response. but you are right, the current kernel does not work after an update. here is what i see on the console:

Uncompressing Linux... done, booting the kernel.
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.16.0-4-kirkwood (debian-kernel@lists.debian.org) (gcc version 4.8.3 (Debian 4.8.3-16) ) #1 Debian 3.16.7-ckt2-1 (2014-12-08)
[    0.000000] CPU: Feroceon 88FR131 [56251311] revision 1 (ARMv5TE), cr=0005397f
[    0.000000] CPU: VIVT data cache, VIVT instruction cache
[    0.000000] Machine model: Buffalo Linkstation LS-CHLv2
[    0.000000] Memory policy: Data cache writeback
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 16256
[    0.000000] Kernel command line: console=ttyS0,115200 root=/dev/sda2
[    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Memory: 55912K/65536K available (3952K kernel code, 361K rwdata, 1452K rodata, 282K init, 293K bss, 9624K reserved, 0K highmem)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xffc00000 - 0xffe00000   (2048 kB)
[    0.000000]     vmalloc : 0xc4800000 - 0xff000000   ( 936 MB)
[    0.000000]     lowmem  : 0xc0000000 - 0xc4000000   (  64 MB)
[    0.000000]     pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
[    0.000000]     modules : 0xbf000000 - 0xbfe00000   (  14 MB)
[    0.000000]       .text : 0xc0008000 - 0xc054f50c   (5406 kB)
[    0.000000]       .init : 0xc0550000 - 0xc0596864   ( 283 kB)
[    0.000000]       .data : 0xc0598000 - 0xc05f24b0   ( 362 kB)
[    0.000000]        .bss : 0xc05f24b0 - 0xc063baac   ( 294 kB)
[    0.000000] NR_IRQS:114
[    0.000025] sched_clock: 32 bits at 166MHz, resolution 6ns, wraps every 25769803770ns
[    0.000545] Console: colour dummy device 80x30
[    0.000586] Calibrating delay loop... 595.96 BogoMIPS (lpj=1191936)
[    0.028117] pid_max: default: 32768 minimum: 301
[    0.028298] Security Framework initialized
[    0.028379] Yama: disabled by default; enable with sysctl kernel.yama.*
[    0.028509] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.028539] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.029821] Initializing cgroup subsys memory
[    0.029888] Initializing cgroup subsys devices
[    0.029975] Initializing cgroup subsys freezer
[    0.030016] Initializing cgroup subsys net_cls
[    0.030087] Initializing cgroup subsys blkio
[    0.030146] Initializing cgroup subsys perf_event
[    0.030183] Initializing cgroup subsys net_prio
[    0.030338] CPU: Testing write buffer coherency: ok
[    0.030511] ftrace: allocating 16505 entries in 33 pages
[    0.077586] Setting up static identity map for 0x3bcc20 - 0x3bcc78
[    0.083810] devtmpfs: initialized
[    0.086877] pinctrl core: initialized pinctrl subsystem
[    0.087717] regulator-dummy: no parameters
[    0.094873] NET: Registered protocol family 16
[    0.095456] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.097175] cpuidle: using governor ladder
[    0.097217] cpuidle: using governor menu
[    0.097610] Feroceon L2: Enabling L2
[    0.097676] Feroceon L2: Cache support initialised.
[    0.098251] [Firmware Info]: /ocp@f1000000/ethernet-controller@72000/ethernet0-port@0: local-mac-address is not set
[    0.098348] [Firmware Info]: /ocp@f1000000/ethernet-controller@76000/ethernet1-port@0: local-mac-address is not set
[    0.107426] No ATAGs?
[    0.115109] platform regulators:regulator@1: Driver reg-fixed-voltage requests probe deferral
[    0.115229] platform regulators:regulator@2: Driver reg-fixed-voltage requests probe deferral
[    0.117272] Switched to clocksource orion_clocksource
[    0.156008] NET: Registered protocol family 2
[    0.157759] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.157805] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.157839] TCP: Hash tables configured (established 1024 bind 1024)
[    0.157929] TCP: reno registered
[    0.157953] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.157989] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.158321] NET: Registered protocol family 1
[    0.158814] Unpacking initramfs...
[    0.163730] Initramfs unpacking failed: junk in compressed archive
[    0.173868] Freeing initrd memory: 2568K (c0801000 - c0a83000)
[    0.176524] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.176672] audit: initializing netlink subsys (disabled)
[    0.176772] audit: type=2000 audit(0.160:1): initialized
[    0.178332] zbud: loaded
[    0.178792] VFS: Disk quotas dquot_6.5.2
[    0.178873] Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.179039] jffs2: version 2.2. (NAND) (SUMMARY)  © 2001-2006 Red Hat, Inc.
[    0.179432] msgmni has been set to 114
[    0.182765] alg: No test for stdrng (krng)
[    0.182947] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
[    0.183289] io scheduler noop registered
[    0.183571] io scheduler cfq registered (default)
[    0.185751] kirkwood-pinctrl f1010000.pin-controller: registered pinctrl driver
[    0.188196] mv_xor f1060800.xor: Marvell shared XOR driver
[    0.205489] mv_xor f1060800.xor: Marvell XOR: ( xor cpy )
[    0.225485] mv_xor f1060800.xor: Marvell XOR: ( xor cpy )
[    0.225808] mv_xor f1060900.xor: Marvell shared XOR driver
[    0.245484] mv_xor f1060900.xor: Marvell XOR: ( xor cpy )
[    0.265483] mv_xor f1060900.xor: Marvell XOR: ( xor cpy )
[    0.266271] Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled
[    0.268557] console [ttyS0] disabled
[    0.268646] f1012000.serial: ttyS0 at MMIO 0xf1012000 (irq = 33, base_baud = 10416666) is a 16550A
[    0.789919] console [ttyS0] enabled
[    0.797511] m25p80 spi0.0: m25p40 (512 Kbytes)
[    0.802004] 3 ofpart partitions found on MTD device spi0.0
[    0.807490] Creating 3 MTD partitions on "spi0.0":
[    0.812291] 0x000000000000-0x000000060000 : "uboot"
[    0.819307] 0x000000060000-0x000000070000 : "dtb"
[    0.826133] 0x000000070000-0x000000080000 : "uboot_env"
[    0.834342] mousedev: PS/2 mouse device common for all mice
[    0.840895] rtc-mv f1010300.rtc: rtc core: registered f1010300.rtc as rtc0
[    0.847990] i2c /dev entries driver
[    0.854490] ledtrig-cpu: registered to indicate activity on CPUs
[    0.860931] TCP: cubic registered
[    0.864291] NET: Registered protocol family 17
[    0.868796] mpls_gso: MPLS GSO support
[    0.873803] registered taskstats version 1
[    0.879485] USB Power: 5000 mV 
[    0.883224] HDD Power: 5000 mV 
[    0.886989] rtc-mv f1010300.rtc: setting system clock to 2000-01-13 14:25:45 UTC (947773545)
[    0.897428] List of all partitions:
[    0.900919] 1f00             384 mtdblock0  (driver?)
[    0.906014] 1f01              64 mtdblock1  (driver?)
[    0.911085] 1f02              64 mtdblock2  (driver?)
[    0.916148] No filesystem could mount root, tried: 
[    0.921039] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    0.929274] CPU: 0 PID: 1 Comm: swapper Not tainted 3.16.0-4-kirkwood #1 Debian 3.16.7-ckt2-1
[    0.937805] [<c000f810>] (unwind_backtrace) from [<c000c4ac>] (show_stack+0x18/0x1c)
[    0.945534] [<c000c4ac>] (show_stack) from [<c03b4fe4>] (panic+0x80/0x1f8)
[    0.952401] [<c03b4fe4>] (panic) from [<c0551170>] (mount_block_root+0x264/0x2ac)
[    0.959867] [<c0551170>] (mount_block_root) from [<c0551344>] (prepare_namespace+0x124/0x184)
[    0.968368] [<c0551344>] (prepare_namespace) from [<c0550dbc>] (kernel_init_freeable+0x1c0/0x208)
[    0.977214] [<c0550dbc>] (kernel_init_freeable) from [<c03b4548>] (kernel_init+0x10/0xec)
[    0.985367] [<c03b4548>] (kernel_init) from [<c0009490>] (ret_from_fork+0x14/0x20)
[    0.992916] ---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)

**Comment by mwalle** [comment]
seems like there are some issues with the kernel decompressor overwriting the initramfs...
you have to set adjust the loading adresses. use the following

      setent bootcmd_legacy 'ide reset && load ide ${hdpart} 0x00800000 /uImage.buffalo && load ide ${hdpart} 0x01000000 /initrd.buffalo && bootm 0x00800000 0x01000000'

this should be equivalent to:

      setent bootcmd_legacy 'ide reset && load ide ${hdpart} ${kernel_addr} /uImage.buffalo && load ide ${hdpart} ${ramdisk_addr} /initrd.buffalo && bootm ${kernel_addr} ${ramdisk_addr}

**Comment by ClashTheBunny** [comment]
You win the Internet.  Not only do you push changes upstream, but you are
the most helpful person on earth.  Thank you so much!

Randall Mason
clashthebunny@gmail.com

**Comment by mwalle** [comment]
fyi, i've just submitted a patch to fix this in upstream u-boot. i've also pushed the changes here on my repository. i also support the bootz command now, which doesn't need any u-boot image header anymore. eg. direct booting of vmlinuz/initrd.gz and dtb.

**Comment by mwalle** [comment]
see http://git.denx.de/?p=u-boot.git;a=commit;h=bc2ad9f04dd9d15e7134f7e1b6386d1995772d69
there is now also a more convenient way to boot debian:
http://git.denx.de/?p=u-boot.git;a=commit;h=4fe49d7becc2dfb7288f8b265e0976428b64323c
