### ISSUE TITLE
linux-image-4.2.0-1-kirkwood not booting

### ISSUE THREAD

**Issue by ClashTheBunny** [mwalle/u-boot#5]
Similar to last time, I've upgraded my kernel and my NAS has died.

If I bootz linux-image-4.2.0-1-kirkwood, the system never seems to come up, never mounts drives, etc.  There is no syslog as before.

If I bootz linux-image-4.1.0-2-kirkwood, I'm back in action.

Here are the linux-images I have installed:
ii  linux-image-4.1.0-2-kirkwood           4.1.6-1                                armel        Linux 4.1 for Marvell Kirkwood
ii  linux-image-4.2.0-1-kirkwood           4.2.3-2                                armel        Linux 4.2 for Marvell Kirkwood
ii  linux-image-kirkwood                   4.2+68                                 armel        Linux for Marvell Kirkwood (meta-package)

I also updated to linux-image-4.2.0-1-kirkwood armel 4.2.5-1 and it doesn't work.
I then tried 4.2.1-2, it also doesn't work.

I'm not sure if 4.2 ever worked.

Any ideas?

**Comment by ClashTheBunny** [comment]
As a side note, the bootz available in later u-boots is SO VERY HELPFUL!  It's so much easier to get a working system because of the ability to use versioned kernels.  Debian not displaying which kernel is contained in the uImage makes life difficult when these types of problems surface.

**Comment by ClashTheBunny** [comment]
I finally figured it out.

I listened closely and figured out that the initramfs was spinning up the hard disk but never finding the root.  I experimented a little and accidentally stumbled upon the bootargs not expanding ${root}.

I've now totally proven it to myself by setting bootargs at the console to:
`sentenv bootargs ${bootargs} ${root}`
when bootargs held:
`bootargs=console=ttyS0,115200 root=${root}`

and the kernel boots up with this:
```[    0.000000] Kernel command line: console=ttyS0,115200 root=${root} root=UUID=3849128d-e415-4f9b-b3b4-d3605bc089fa```

I don't know if this is a general bug, but this u-boot is the stock git.denx.de at the v2015.10 tag.  What should be my next step in diagnosing this?  At least my booting problem is fixed, and it had nothing to do with upgrading the kernel.  It was probably that the new initramfs didn't have a hint as to what root should be like the old versions of initramfs and the root=${root} part of bootargs has never worked.  I noticed that on my lacie network space v2 that I don't need any root on the bootargs because the initramfs has it's own internal hint:
```
cat conf/conf.d/default_root 
ROOT="/dev/disk/by-uuid/0a2ae300-2b39-409e-a5d2-f4451a60688c"
```
but that file doesn't exist on my LS-XHL.

**Comment by mwalle** [comment]
Hi Randall,

sorry for this late answer, but I've been busy lately.

> I finally figured it out.

ok good ;)

> I listened closely and figured out that the initramfs was spinning up
> the hard disk but never finding the root. I experimented a little and
> accidentally stumbled upon the bootargs not expanding ${root}.
> 
> I've now totally proven it to myself by setting bootargs at the
> console to:
>  sentenv bootargs ${bootargs} ${root}
>  when bootargs held:
>  bootargs=console=ttyS0,115200 root=${root}

where does the root=${root} come from? Debian? The default u-boot 
environment hardcodes this to root=/dev/sda2.

> and the kernel boots up with this:
>  [ 0.000000] Kernel command line: console=ttyS0,115200 root=${root}
> root=UUID=3849128d-e415-4f9b-b3b4-d3605bc089fa
> 
> I don't know if this is a general bug, but this u-boot is the stock
> git.denx.de at the v2015.10 tag. What should be my next step in
> diagnosing this?

u-boot does not evaluate any variables in the bootargs variable. This is 
not a bug. And I guess this won't be changed soon.

So again, if this comes from debian, this is a bug there.

> At least my booting problem is fixed, and it had
> nothing to do with upgrading the kernel. It was probably that the new
> initramfs didn't have a hint as to what root should be like the old
> versions of initramfs and the root=${root} part of bootargs has never
> worked. I noticed that on my lacie network space v2 that I don't need
> any root on the bootargs because the initramfs has it's own internal
> hint:
> 
> cat conf/conf.d/default_root
> ROOT="/dev/disk/by-uuid/0a2ae300-2b39-409e-a5d2-f4451a60688c"
> 
> but that file doesn't exist on my LS-XHL.

This is a UUID (unique to exactly this partition on this device) and is 
usually a link to /dev/sdXY.

-michael

**Comment by ClashTheBunny** [comment]
I was trying to be too smart with u-boot variables!  Thanks so much!

Randall Mason
randall@mason.ch
