### ISSUE TITLE
4TB drive with U-Boot 2013.01.01 not booting

### ISSUE THREAD

**Issue by benoqkuke** [mwalle/u-boot#6]
Hi, 

I've upgraded my u-boot to the one you provided several year back. Lately my HDD crashed and I bought a new 4TB.
I prepared the disk for Debian install but my LS-XHL doesn't boot. 
Using the recovery mode, I accessed the console and here's what I have:

=> run bootcmd_hdd

Reset IDE: Bus 0: OK 
  Device 0: Model: WDC WD40EFRX-XXXXXX Firm: 82.00A82 Ser#:  WD-XXXXXXX
            Type: Hard Disk
            Supports 48-bit addressing
            Capacity: 1718295.8 MB = 1678.0 GB (-775897424 x 512)
GPT: last_usable_lba incorrect: 1D1C0BE8E > D1C0BEB0
get_partition_info_efi: *** ERROR: Invalid GPT ***
** Invalid partition 1 **

=> id part 0

Partition Map for IDE device 0  --   Partition Type: EFI

GPT: last_usable_lba incorrect: 1D1C0BE8E > D1C0BEB0
print_part_efi: *** ERROR: Invalid GPT ***

So uBoot only see 1.6TB. Looks like uBoot is not supporting the 4TB drive. Is this a known issue ? Is there a newer version which fixes that ? By any chance do you have a compiled version (and tested ;) ) that I can use ?

Ben

**Comment by benoqkuke** [comment]
I compile from debian 2018.9 and load it on my LS-XHL using
`setenv serverip <IP of TFTP server>`
`tftpboot u-boot.kwb`
`sf probe 0`
`sf erase 0 +$filesize`
`sf write $fileaddr 0 $filesize`
`reset`

And the 4TB disk is now properly detected.

This issue can be closed

**Comment by mwalle** [comment]
yes newer bootloader has support for 1.6+ TB disks. IIRC you have to use GPT.
